### ISSUE TITLE
:bug: 上传 bytes 类型图片时出现 I/O 错误

### ISSUE THREAD

**Issue by zhulinyv** [mobyw/nonebot-plugin-smms#1]
感谢大佬的插件, 传 Path 没有问题, 但是传 bytes 会报错.

Nonebot 版本: 2.2.1

[nonebot-plugin-smms](https://github.com/mobyw/nonebot-plugin-smms) 版本: 0.1.0

![image](https://github.com/mobyw/nonebot-plugin-smms/assets/66541860/21c8bcea-2d82-442c-b766-1a0bbbd9db3a)

**Comment by mobyw** [comment]
传入参数前使用 `type()` 查看一下实际传入的类型是不是 `bytes`

**Comment by zhulinyv** [comment]
打扰了, 我忘记 `.read()`
